### PR TITLE
Added instructions for how to use new features while having to support older REDCap versions

### PR DESCRIPTION
**Pull request by mmcev106**
Let me know what y'all think.

### CODE REVIEW

**Comment by kcmcg** [comment]
Should we add a note about using method_exists to use the parent method if available? It does make it slightly more forward compatible and eliminates a potential, if very unlikely, case where we need to update the EM Framework function for a new version of REDCap and end up needing to update the module a second time.

**Comment by scottjpearson** [comment]
I agree completely with Kyle's recommendation to add something to call `parent::<METHOD>()` if the parent method exists, as suggested in Kyle's Sharepoint. That relieved some consternation when I implemented it yesterday.

**Comment by mmcev106** [comment]
@kcmcg & @scottjpearson, I think my latest commits address your concerns.  What do you think?

**Review by scottjpearson — APPROVED** [review]
Yes, that's much more explicit. I can't think of any other improvements.

**Review by kcmcg — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
