### PR TITLE
Adding to new-hooks.md file

### PR DESCRIPTION
**Pull request by alanisem123**
Additional context is being added to the document describing how to add a new hook. One file are being modified (new-hooks.md) and one image is being added (BasicEMHookExample.PNG).

### CODE REVIEW

**Review by mmcev106 — CHANGES_REQUESTED** [review]
@alanisem123, this looks like a great improvement overall.  Thank you for working on it!  I did have several minor feedback items that I'm curious to hear your thoughts on:

- I believe we should use the prefix “redcap_module_” in the pic and a few places in the text.
- Should we include some parameters in the example in the pic?
- I think it might be worth giving the module a more typical name in the pictured example.  People would never actually name a module “AddHook”.  I’ve found that oddities like this in the docs tend to confuse people.  It might be helpful to make the module “MyTestModule” or something that more clearly describes what it is.
- The phrasing “the actual hook” is confusing to me.  In my mind “the actual hook” is the implementation of the hook in each module.
- Instead of using “redcap_every_page_before_render” as an example, should we use one of the “redcap_module_” hooks?
- Why does it say “must have a minimum framework version of 12”?  I’m hesitate to hard code a specific framework version in the docs as that recommendation changes with each LTS release.  Also, directions for setting the framework version should likely exist on a different page that is about writing your first module (not on a page about adding hooks).
- I don’t think we should say the new hook is not allowed to have a return value.  There are cases where a return value will be required.
- The following sentence jumps out as very odd to me: “The module doesn't need to be enabled on all project by default for its method to be used by the callHook method”.  Why would anyone think that?  Is there something misleading in the docs about this elsewhere that we should correct?

**Comment by mmcev106** [comment]
Does this input help clarify those two items?

- How do you feel about replacing the return value line with the following: "It is possible to add hooks with return values, but this also requires updating the `filterHookResults()` method to support the new hook, including handling when multiple modules potentially returning conflicting values."

- The primary audience for these docs is beginner to intermediate module developers, as advanced developers can create modules without them.  With this in mind, I'm now feeling fairly strongly that "the actual hook" and the word "hook" in general should refer to the implementation in each module.  When you tell someone to add a "hook" to a module, it is implied that the implementation is what is being discussed.  I would say that "hooks" live in modules, while the framework and REDCap core only provide the means of adding hooks.

**Comment by alanisem123** [comment]
Yes, I think that sounds reasonable. I'll close this pull request and start a new one ASAP. Thanks,

**Comment by mmcev106** [comment]
If you like, feel free to reopen this & add to or replace this branch.

**Pull request closed without merging**
