### PR TITLE
Deprecated getChoiceLabel()

### PR DESCRIPTION
**Pull request by mmcev106**
@paulj3, what do you think of this in lieu of [this PR](https://github.com/vanderbilt-redcap/external-module-framework/pull/637)?

### CODE REVIEW

**Comment by mmcev106** [comment]
@JohnOfTheWater, I'm sorry for tagging you accidently.  You can ignore this!

**Comment by paulj3** [comment]
@mmcev106 when I tried out the `$module->getChoiceLabels($fieldName)[$value]`, I only tried it in my particular case, which was a set or radio button choices.  What about the other cases `getChoiceLabel()` support? such as `truefalse`, `yesno`, `text_validation_type_or_show_slider_number` or `sql`? Does `$module->getChoiceLabels($fieldName)[$value]` cover these cases?  If you already know, great. If not, I have bandwidth to do some legwork.  

If our proposed solution doesn't cover these cases, we should explicitly outline the supported `field_types`.

**Comment by scottjpearson** [comment]
For what my opinion is worth, this design makes sense. The old method pulled individual values from the database. If used sequentially, it requires queries for each label requested. Instead, this approach encourages them to be pulled only once per field - a more optimized approach.

**Comment by mmcev106** [comment]
@paulj3, you're absolutely right.  The singular method supports field types than the plural method.  Please forgive me trying to oversimplify this.  Closing...

**Pull request closed without merging**
