### PR TITLE
Add description of proposed new hook: redcap_module_api_before

### PR DESCRIPTION
**Pull request by AndrewPoppe**
This hook is triggered when REDCap is about to call an API method.

### CODE REVIEW

**Comment by mmcev106** [comment]
This is next on my list after #599 is merged!

**Comment by mmcev106** [comment]
@AndrewPoppe, I wanted to let you know I haven't forgotten this!  The minimum PHP version required by REDCap may be changing in the spring.  If we are able to bump it up to 8, it may be worth slow rolling this so that we can use named parameters to really set a good standard for new module only hooks going forward.  I'm hoping to get an answer on that in the next week or two.

**Comment by mmcev106** [comment]
@AndrewPoppe, I just added a couple of commits to this PR and would be curious to hear your perspective on them.  We've decided on 7.4 as the new min PHP version. I'd like to delay our plan for using named parameters via an array as it adds complications to the EM source code. It would likely be more prudent to wait to revisit that until after PHP 8 is the min supported version in REDCap, and just follow existing patterns for now.  I'm currently considering the following call signature in API/index.php, plus couple of lines in the EM framework prefixing any errors with `The some_prefix module rejected this API request with the following error:`.  What you do think?

```php
$moduleError = \ExternalModules\ExternalModules::callHook('redcap_module_api_before', [
	defined('PROJECT_ID') ? PROJECT_ID : null,
	array_merge($post, ['action' => $action])
]);

if($moduleError !== null){
	RestUtility::sendResponse(403, $moduleError);
}
```

**Comment by AndrewPoppe** [comment]
@mmcev106  That all makes sense to me. My only concerns surround the error process and messaging.

1. What happens if an `exitAfterHook` is called within the `redcap_module_api_before` hook? Will that exit the script after the `callHook`? I've never actually looked to see how that is implemented.
2. End users may be confused about that prefix to the error message - they may not even know what a module is or that a particular module is enabled in the project.
3. How is translation of that message done?

These are all minor concerns.

**Comment by mmcev106** [comment]
@AndrewPoppe,

1. Yes, calling `exitAfterHook()` will cause the hook to exit after `callHook()`, just like any other hook.
2. I mainly added the error prefix to avoid confusion if a module exits with an ambiguous message (making it unclear why the API call failed).  This could get especially confusing if two modules ever implement this hook at the same time with different criteria and generic responses like "Request not allowed".  I think it is important for API users to have the ability to know specifically why a request failed (and up to them as to whether they want to put in the effort to fully understand the message).
3. I'll set up the error prefix string for translation just like all the others (in English.ini).

What are your thoughts on all that?  Don't hesitate to speak up if you have concerns or a different perspective on things!  I am really appreciative to have someone else interested in the details.

**Comment by AndrewPoppe** [comment]
I think that all makes sense to me!

**Comment by mmcev106** [comment]
@AndrewPoppe, this is officially completed a PR has been sent to Rob which will likely be included in an upcoming release!  Here are the associated PRs for anyone who is curious:

https://github.com/vanderbilt-redcap/REDCap/pull/2080
https://github.com/vanderbilt-redcap/external-module-framework/pull/609

**Pull request merged**
